### ISSUE TITLE
WithApplicationComponents causing java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jsw** [playframework/scalatestplus-play#102]
I'm using play 2.6.1 and scalatestplus-play 3.1.0

My test code looks roughly like
```
27: class CallbackControllerTest extends PlaySpec with OneAppPerSuiteWithComponents {
...
38: override def components: BuiltInComponentsFromContext = new BuiltInComponentsFromContext(context) with NoHttpFiltersComponents {
39:     import play.api.routing.Router
40:     lazy val router: Router = Router.empty
41:  }
```

At runtime I get 

```
[info] com.ebay.n.bot.controllers.CallbackControllerTest *** ABORTED ***
[info]   java.lang.NoSuchMethodError: play.api.ApplicationLoader$.createContext$default$5()Lplay/api/inject/DefaultApplicationLifecycle;
[info]   at org.scalatestplus.play.components.WithApplicationComponents$class.context(WithApplicationComponents.scala:37)
[info]   at controllers.CallbackControllerTest.context$lzycompute(CallbackControllerTest.scala:27)
[info]   at controllers.CallbackControllerTest.context(CallbackControllerTest.scala:27)
[info]   at controllers.CallbackControllerTest$$anon$2.<init>(CallbackControllerTest.scala:38)
[info]   at controllers.CallbackControllerTest.components(CallbackControllerTest.scala:38)
[info]   at controllers.CallbackControllerTest.components(CallbackControllerTest.scala:27)
[info]   at org.scalatestplus.play.components.WithApplicationComponents$class.newApplication(WithApplicationComponents.scala:30)
[info]   at controllers.CallbackControllerTest.newApplication(CallbackControllerTest.scala:27)
[info]   at org.scalatestplus.play.components.OneAppPerSuiteWithComponents$class.fakeApplication(OneAppPerSuiteWithComponents.scala:141)
[info]   at controllers.CallbackControllerTest.fakeApplication(CallbackControllerTest.scala:27)
```

Am I doing something wrong? My goal is to obtain an instance of `ControllerComponents` so that I may test my compile-time DI Controllers.

**Comment by cchantep** [comment]
I would suggest to first check the dependencies using `dependencyTree` in SBT, guessing there are version conflicts for some Play libs.

**Comment by marcospereira** [comment]
@jsw can you confirm that using ScalaTest+Play 3.1.1 and Play 2.6.2 fixes the problem?

**Comment by jsw** [comment]
@marcospereira Confirmed. Thanks for the fix and update. 👍 

BTW: In the meantime, my workaround was to use the following, which is also more succinct. I'm not sure what the pros/cons are otherwise.

```
class ExampleControllerTest extends PlaySpec with StubControllerComponentsFactory {
...
  new ExampleController(stubControllerComponents(playBodyParsers = stubPlayBodyParsers(app.materializer)))
```
